import {
    UserIcon,
    EyeIcon,
    CurrencyDollarIcon,
    Cog6ToothIcon,
    GlobeAltIcon,
    MoonIcon,
    ArrowLeftStartOnRectangleIcon,
    BookOpenIcon,
    QuestionMarkCircleIcon,
    AcademicCapIcon,
    Bars3Icon,
    XMarkIcon,
    Bars4Icon,
    XCircleIcon,
    ArrowUpRightIcon,
    ChevronDoubleDownIcon,
    ShieldCheckIcon,
    Squares2X2Icon,
    WalletIcon,
    WrenchScrewdriverIcon,
    LockClosedIcon,
    Cog8ToothIcon
} from "@heroicons/react/24/outline";
import { Link, Route, Routes, BrowserRouter, useLocation } from "react-router-dom"


export {
    UserIcon,
    EyeIcon,
    CurrencyDollarIcon,
    Cog6ToothIcon,
    GlobeAltIcon,
    MoonIcon,
    ArrowLeftStartOnRectangleIcon,
    BookOpenIcon,
    QuestionMarkCircleIcon,
    AcademicCapIcon,
    Bars3Icon,
    XMarkIcon,
    Bars4Icon,
    XCircleIcon,
    Link, Route, Routes, BrowserRouter, useLocation,
    ArrowUpRightIcon,
    ChevronDoubleDownIcon,
    ShieldCheckIcon,
    Squares2X2Icon,
    WalletIcon,
    WrenchScrewdriverIcon,
    LockClosedIcon,Cog8ToothIcon
}